# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  
  imageNameAPI: 'actio.api:$(Build.BuildId)'
  imageNameServiceIdentity: 'actio.services.identity:$(Build.BuildId)'
  imageNameServiceActivities: 'actio.services.activities:$(Build.BuildId)'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    #displayName: 'dotnet build $(buildConfiguration)'
    dotnet test Actio.API.Tests --configuration $(buildConfiguration) --logger trx
    
    dotnet publish --configuration $(buildConfiguration) --output out
    docker build -f Dockerfile-api -t $(dockerId)/$(imageNameAPI) .
    docker login -u $(dockerId) -p $pswd
    docker push $(dockerId)/$(imageNameAPI)
    
    
    
    #dotnet test Actio.Services.Identity.Tests --configuration $(buildConfiguration) --logger trx
    #dotnet test Actio.Services.Activities.Tests --configuration $(buildConfiguration) --logger trx
  env:
    pswd: $(dockerPassword)

- task: PublishTestResults@2
  condition: succeeded()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
